module:
  mounts:
    - source: archetypes
      target: archetypes
    - source: assets
      target: assets
    - source: content
      target: content
    - source: i18n
      target: i18n
    - source: layouts
      target: layouts

# Default
permalinks:
  services_categories: /services/tags/:slug/
taxonomies:
  services_tag: services_categories
